tas2580_wiki_index:
    pattern: /kb/
    defaults: { _controller: tas2580.wiki.overview:base }

tas2580_wiki_article:
    path: /kb/{article}
    defaults: { _controller: tas2580.wiki.main:article, article: "" }


